#dev-server docker file

#pull offical base image
FROM python:3.9.6-alpine

#set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

#set work directory
WORKDIR /usr/src/app

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN apk add zlib-dev jpeg-dev gcc musl-dev

#install dependencies
RUN pip install --upgrade pip
#copy requirements.txt to work dir
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy and run entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

#copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
