# Generated by Django 3.2.8 on 2021-11-19 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField(default=True)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
                ('IsAnswer', models.BooleanField(default=False)),
                ('Quiz_Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_User_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_Correct', models.IntegerField()),
                ('Time_Taken', models.DurationField()),
                ('DateOfAttempt', models.DateTimeField(auto_now_add=True)),
                ('Quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question_User_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsCorrect', models.BooleanField(default=False)),
                ('Quiz_Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_question')),
                ('Quiz_Question_Option_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_question_option')),
                ('User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.user')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='Genre_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz_genre'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.user'),
        ),
    ]
