# Generated by Django 3.2.8 on 2021-11-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Genre_ID',
            new_name='Genre',
        ),
    ]
