# Generated by Django 3.2.9 on 2021-11-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_genre_id_quiz_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='Number',
        ),
        migrations.AlterField(
            model_name='quiz_question_option',
            name='IsAnswer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
