# Generated by Django 4.0 on 2021-12-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quizzes', '0003_auto_20211124_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quiz_question_user_answer',
            name='Quiz_User_Attempt_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_user_attempt'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='quiz_question_user_answer',
            name='Quiz_Question_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_question'),
        ),
        migrations.AlterField(
            model_name='quiz_question_user_answer',
            name='Quiz_Question_Option_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz_question_option'),
        ),
        migrations.AlterField(
            model_name='quiz_question_user_answer',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='quiz_user_attempt',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
