# Generated by Django 3.2.9 on 2021-12-12 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20211211_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_user_attempt',
            name='DateOfAttempt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz_user_attempt',
            name='Number_Correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz_user_attempt',
            name='Time_Taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
